### ISSUE TITLE
Improve arbitrary function generation

### ISSUE THREAD

**Issue by rickynils** [rickynils/scalacheck#136]
This has been discussed for some time. The current way of generating functions are quite stupid, since it will only generate constant functions.

#66 does some changes in this area, but it must be updated to current master. And maybe we should take the Haskell QuickCheck route instead, using some fashion of CoArbitrary.

**Comment by tonymorris** [comment]
CoArbitrary, as in Haskell, is not possible given the `Gen` implementation (returning `Option`).

**Comment by pocketberserker** [comment]
I tried to implement CoArbitrary pocketberserker@4293d29 and replace arbitrary function implementation pocketberserker@169d1e4 .

**Comment by jedesah** [comment]
As a side note, it would be really nice if the generated functions could have a nice `toString` method. When trying to figure out why your property fails, it sort of sucks to see `<function2>` as the representation of the function that was generated.

I took a stab at a version that uses reflection, and one of the advantages of this approach is that it is possible to generate functions like so:

    object Take extends String => String {
      def apply(a: String): String = take(a)
      def toString = "take(_)"
    }

But I think reflection is an inferior approach to `CoArbitrary`. One might use reflection to automate generation of some `CoArbitrary` or something, but it should not be the main mechanism of generation since that would not allow to take advantage of the type system for customization.

Just something to keep in mind.

Is anyone working on this right now? Is there an estimate?

**Comment by non** [comment]
Hello, is there any plan to improve function generation for Scalacheck, either along the lines of @pocketberserker's work, or another way?

**Comment by xuwei-k** [comment]
pocketberserker's codes still does not work correctly due to mutable random generator(`scala.util.Random`)

Maybe there are 2 ways
- immutable random number generator + State monad like( [I have implemented](https://github.com/scalaprops/scalaprops/blob/v0.1.7/core/src/main/scala/scalaprops/Gen.scala#L9) )
- murable random number generator + IO monad like (Haskell's QuickCheck ?)

**Comment by xuwei-k** [comment]
> As a side note, it would be really nice if the generated functions could have a nice toString


> Is anyone working on this right now? Is there an estimate?

work in progress
- https://github.com/scalaprops/scalaprops/commit/4b48db01cc590a0678
- https://github.com/nick8325/quickcheck/blob/2.8.1/Test/QuickCheck/Function.hs#L8

**Comment by non** [comment]
I created a branch to update Scalacheck to use an immutable RNG, and created a basic Cogen type there. I was able to hack together a Gen[A => B] which produces deterministic, but non-constant, functions:

https://github.com/non/scalacheck/blob/topic/immutable-rng/src/main/scala/org/scalacheck/Gen.scala#L614

The warts around using Option are still there -- I may try something a bit more radical.

@rickynils, is this direction something you'd like to see in a PR?
