### ISSUE TITLE
Test report is wrong when `fork in Test := true`

### ISSUE THREAD

**Issue by tkawachi** [rickynils/scalacheck#185]
Following test unexpectedly succeeds when `fork in Test := true`.

``` scala
import org.scalacheck.Properties
object Spec1 extends Properties("Spec1") {
  property("prop 1") = false
  property("prop 2") = true
}
```

```
[info] ! Spec1.prop 1: Falsified after 0 passed tests.
[info] + Spec1.prop 2: OK, proved property.
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[success] Total time: 4 s, completed Jul 21, 2015 10:45:18 PM
```

I confirmed this issue was introduced by 82042613eebbde3c822328cbfab3c4186828f1f1 using `git bisect`.

Tested by sbt 0.13.8 and scalacheck 1.12.4.

**Comment by xuwei-k** [comment]
+1

**Comment by rickynils** [comment]
Weird. Will look into this after my vacation.

**Comment by gok01172** [comment]
The number of total tasks is wrong when `fork in Test := true` 

```scala
import org.scalacheck.Properties

object Spec1 extends Properties("Spec1") {
  property("prop 1") = false
  property("prop 2") = true
}
```

```
[info] + Spec1.prop 1: OK, proved property.
[info] + Spec1.prop 2: OK, proved property.
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 351 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 1 s, completed Jan 18, 2016 4:18:28 PM
```

There are two properties checked, but sbt prints `Total 1`. Without fork, it gives

```
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
```

**Comment by k0ala** [comment]
I also observe this with version 1.12.5

**Comment by dwijnand** [comment]
People interested in this bug might want to see if sbt 0.13.13-RC1 fixes it for them: https://github.com/sbt/sbt/pull/2730

**Comment by Philippus** [comment]
this bug is still there for me in sbt 0.13.13

**Comment by lihaoyi** [comment]
This sounds a lot like https://github.com/lihaoyi/utest/issues/25 caused by https://github.com/sbt/sbt/issues/3510 (uTest's workaround is linked from the utest issue)

**Comment by retronym** [comment]
We ran into this in the Scala build as well and I disabled forking. Turns out that took us out of the frying pan and into the [fire](https://github.com/scala/scala/pull/6300#issuecomment-372495182), as we now get the wrong version of scala-library on the Scalacheck classpath.

So its time to fix this bug :)

When forking tests, the SBT process setup up a server that listens on a stream for events sent by the forked JVM.

This [code](https://github.com/sbt/sbt/blob/684e2c369269e2aded5861c06aaad6f0b6b70a30/main/actions/src/main/scala/sbt/ForkTests.scala#L135-L143) in the server:

```scala
  @annotation.tailrec def react(): Unit = is.readObject match {
    case `Done` =>
      os.writeObject(Done); os.flush()
    case Array(`Error`, s: String) =>
      log.error(s); react()
    case Array(`Warn`, s: String) =>
      log.warn(s); react()
    case Array(`Info`, s: String) =>
      log.info(s); react()
    case Array(`Debug`, s: String) =>
      log.debug(s); react()
    case t: Throwable =>
      log.trace(t); react()
    case Array(group: String, tEvents: Array[Event]) =>
      listeners.foreach(_ startGroup group)
      val event = TestEvent(tEvents)
      listeners.foreach(_ testEvent event)
      val suiteResult = SuiteResult(tEvents)
      results += group -> suiteResult
      listeners.foreach(_ endGroup (group, suiteResult.result))
      react()
  }
```

Assumes that all events for a given `group` will be sent in a single batch (`results` is a `Map`, not a `MultiMap`)

The Scalacheck Framework seems to violate this assumption by creating a different `Task` for each property. This [calls `handleEvent`](https://github.com/rickynils/scalacheck/blob/148eaad7706cebcc520e3c1289ff7b4447efa4e8/src/main/scala/org/scalacheck/ScalaCheckFramework.scala#L125), which is [implemented by the SBT framework](https://github.com/sbt/sbt/blob/684e2c369269e2aded5861c06aaad6f0b6b70a30/testing/agent/src/main/java/sbt/ForkMain.java#L294) to batch up events from the task and send them up to the server [after task completion](https://github.com/sbt/sbt/blob/684e2c369269e2aded5861c06aaad6f0b6b70a30/testing/agent/src/main/java/sbt/ForkMain.java#L305).

The [test interface](https://github.com/sbt/test-interface/) isn't documented, AFAICT, so this sort of misunderstanding isn't surprising.

I'm going to try to modify Scalacheck to use coarser grained tasks. I might also try to patch SBT to use a multi-map to just deal with the way events are coming.
