### ISSUE TITLE
Gen.choose[Int] out of bounds

### ISSUE THREAD

**Issue by scalasolist** [rickynils/scalacheck#189]
I'm just getting started with ScalaCheck. I use Gen.choose(1, 1000) to generate input for a function that requires non-negative value (and subtracts it until get less or equal to 0). Supplying 0 to the function led it to infinite loop. And 0 was actually generated by Gen.Choose(1, 1000). At first I was puzzled by sudden hungup, but then added debug output and discovered that 0 value was eventually passed to the function.

This issue is reproducing always. Scalacheck version 1.12.4

I tried Gen.choose(1l, 1000l) and it worked correctly, no values outside bounds was generated. So the only Int should be considered.

**Comment by WellingR** [comment]
I believe if you have shinking enabled (which is the default), then the Shrinking process can produce values which could not have been generated by the generator itself.

Since there is no default `Shrink` for `Long` (but there is for `Int`), you only see this issue when generating integers.

**Comment by scalasolist** [comment]
Is it possible to restrict shrinking domain?

**Comment by WellingR** [comment]
I believe you can call the `filter` or `suchThat` functions on your generator for this.
e.g. `Gen.choose(1, 1000).suchThat(_ > 0)`.
The condition in the suchThat block will be ensured not only when generating values, but also when shrinking.

Alternatively you can use implications in your testcases (see the scalacheck user guide for some examples)

**Comment by rickynils** [comment]
@scalasolist: As @WellingR mentions, the shrinking is not perfect, it can sometimes generate values that was not originally generated. Using implications is probably the best way to work around this, and it will also make clear what preconditions your method has.

One thing to notice; when the shrinking process starts, that is because ScalaCheck actually has found an error for an original, non-shrinked value. So even if you get this, admittedly confusing, situation there actually is a bug in your method under test (or in your test).
