### ISSUE TITLE
Arbitrary instance for Char

### ISSUE THREAD

**Issue by lunaryorn** [rickynils/scalacheck#247]
I'd like to generate non-BMP strings with scalacheck, essentially to check whether our code base copes with emojis and all sorts of other strange unicode chars users might enter on their phones.

I tried to figure out whether scalacheck might already have be covered here, and came across the current Arbitrary[Char] instance which looks rather… sophisticated:

```scala
 /** Arbitrary instance of Char */
  implicit lazy val arbChar: Arbitrary[Char] = Arbitrary(
    Gen.frequency(
      (0xD800-Char.MinValue, Gen.choose[Char](Char.MinValue,0xD800-1)),
      (Char.MaxValue-0xDFFF, Gen.choose[Char](0xDFFF+1,Char.MaxValue))
    )
```

What's the reason for "Gen.frequency" and the exclusion of some char ranges?  

The instance used to be `Gen.choose(Char.MinValue, Char.MaxValue)`, but a long time ago the current instance was introduced in c0f3c0d42067807706b54bbc95a9eeed66182b46.  Unfortunately the commit message is very, uhm, "brief", and it's not Github's issue #78 it refers to obviously.

Can anyone shed a light on this rather peculiar instance?  Am I missing something very obvious?

**Comment by phipsgabler** [comment]
I'm not a developer of this, but the range 0xD800 to 0xDFFF are the [surrogate characters](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates), used to encode chars outside of the BMP. Since these only make sense in pairs (high + low), generating them individually seems of no use (according to the link, "isolated surrogate code points have no general interpretation").

The `Gen.frequency` is needed to make the distribution uniform; with just a `Gen.oneOf` of the two blocks, the generated values would be right skewed, so they are weighed by their lengths to compensate that.

In order to generate stuff outside the BMP, I suppose you have to write your own generator. Or probably, there already exists such a thing somewhere...

**Comment by lunaryorn** [comment]
@phipsgabler Thanks, that's very enlightening.  :+1: :clap:

**Comment by non** [comment]
Is this issue solved? Mind if we close this @lunaryorn?

For reference, here's a generator that can choose any 16-bit unsigned character value:

```scala
val g: Gen[Char] = Gen.choose(0.toChar, 0xffff.toChar)
```

This can be passed directly to `forAll` or wrapped in `Arbitrary(...)` to produce an `Arbitrary[Char]` value.

**Comment by lunaryorn** [comment]
Oh yes, of course, closing right away.

**Comment by lunaryorn** [comment]
Sorry :blush: I meant to close it right after the explanation, but apparently pressed the wrong button… I'm constantly confusing them 😕
