### ISSUE TITLE
Regression in `Gen.calendar`

### ISSUE THREAD

**Issue by nrinaudo** [rickynils/scalacheck#295]
It would appear that `Gen.calendar` somehow uses the current system time in `1.13.3`. Here's a test cases that exhibits this behaviour:

```scala
import org.scalatest.FunSuite
import org.scalatest.prop.GeneratorDrivenPropertyChecks
import java.util.Date
import org.scalacheck._

class Repr extends FunSuite with GeneratorDrivenPropertyChecks {
   test("reproduce") {
    forAll { (s: String, g: String => Date) =>
      val d1 = g(s)
      Thread.sleep(100)
      val d2 = g(s)

      assert(d1 === d2)
    }
  }
}
```

This consistently fails under `1.13.3`, with dates that are 100ms appart. It systematically passes in `1.12.5`, however.

Here's a [discussion](https://gitter.im/typelevel/general?at=5817a5467b15d16e55cc9cd7) on the subject in gitter.

**Comment by non** [comment]
Just a note here: the title of this bug is somewhat misleading. In 1.12.5 generated functions always produced constant values, which meant that the same date would always be produced. The function generation is a red herring here, you'll see the same issue with:

import org.scalacheck._
import Prop._

val p = forAll { (n: Long) =>
  val params = Gen.Parameters.default
  val seed = rng.Seed(n)
  val c0 = Gen.calendar(params, seed).get
  Thread.sleep(5)
  val c1 = Gen.calendar(params, seed).get
  c0.getTime == c1.getTime
}

p.check
```
