### ISSUE TITLE
Test.Parameters.Default removed but 1.13.4.jar contains it

### ISSUE THREAD

**Issue by xuwei-k** [rickynils/scalacheck#318]
- https://github.com/rickynils/scalacheck/commit/259607f788ce9d32ff86515ab1648797284b94d1
- https://github.com/rickynils/scalacheck/blob/1.13.4/src/main/scala/org/scalacheck/Test.scala#L107-L126

```
$ zipinfo ~/.ivy2/cache/org.scalacheck/scalacheck_2.12/jars/scalacheck_2.12-1.13.4.jar  | grep Default
-rw----     2.0 fat     2478 bl defN  1-Nov-16 14:27 org/scalacheck/Test$Parameters$Default.class
-rw----     2.0 fat      969 bl defN  1-Nov-16 14:27 org/scalacheck/Gen$Parameters$Default.class
-rw----     2.0 fat     1883 bl defN  1-Nov-16 14:27 org/scalacheck/Test$Parameters$Default$$anon$5.class
$ zipinfo ~/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.13.4.jar  | grep Default
-rw----     2.0 fat     1861 bl defN  1-Nov-16 14:26 org/scalacheck/Test$Parameters$Default$class.class
-rw----     2.0 fat      803 bl defN  1-Nov-16 14:26 org/scalacheck/Gen$Parameters$Default$class.class
-rw----     2.0 fat     1809 bl defN  1-Nov-16 14:26 org/scalacheck/Test$Parameters$Default$$anon$5.class
-rw----     2.0 fat      587 bl defN  1-Nov-16 14:26 org/scalacheck/Gen$Parameters$Default.class
-rw----     2.0 fat     1572 bl defN  1-Nov-16 14:26 org/scalacheck/Test$Parameters$Default.class
$ zipinfo ~/.ivy2/cache/org.scalacheck/scalacheck_2.10/jars/scalacheck_2.10-1.13.4.jar  | grep Default
-rw----     2.0 fat     1464 bl defN  1-Nov-16 14:25 org/scalacheck/Test$Parameters$Default.class
-rw----     2.0 fat      539 bl defN  1-Nov-16 14:25 org/scalacheck/Gen$Parameters$Default.class
-rw----     2.0 fat     1852 bl defN  1-Nov-16 14:25 org/scalacheck/Test$Parameters$Default$class.class
-rw----     2.0 fat      794 bl defN  1-Nov-16 14:25 org/scalacheck/Gen$Parameters$Default$class.class
-rw----     2.0 fat     1762 bl defN  1-Nov-16 14:25 org/scalacheck/Test$Parameters$Default$$anon$5.class
```

**Comment by rickynils** [comment]
OK, I just reproduced this locally by checking out the `1.13.4` tag and running `sbt package`. Then I got the `Default` classes in the (newly created) jar. However, after running `sbt clean` and then `package`, the `Default` classes disappeared from the jar. So clearly I haven't run `clean` before publishing 1.13.4, and sbt doesn't seem to make sure only relevant `.class`-files are included in the package. It seems sbt just grabs everything it kind find in the `classes` directory.

I will have to release 1.13.5 with no source changes since 1.13.4, just to get un-corrupt jars.

**Comment by rickynils** [comment]
I've published ScalaCheck 1.13.5 to fix this issue. https://github.com/rickynils/scalacheck/blob/1.13.5/RELEASE

**Comment by SethTisue** [comment]
The way you've fixed this causing me trouble in the community build (https://github.com/scala/community-builds/issues/493). I'd rather not have to fork ScalaCheck to undo the change. Is there some other way you could fix this, other than by changing the behavior of the

**Comment by SethTisue** [comment]
In the Scala community build, this change confuses dbuild, resulting in https://github.com/scala/community-builds/issues/493

Is there some other way you could fix this? Perhaps by modifying `tools/travis-deploy.sh` appropriately instead...?

**Comment by SethTisue** [comment]
the problem is reproducible outside of dbuild simply by running `jvm/publish` twice in a row. the first run fails with "Access ... was refused by the server: Unauthorized", as expected. but then the second run gives the "Missing files for publishing" error. I think the issue is that you've basically cut the legs out from under `packageBin` by telling it to delete the same files that it needs to produce a result. depending on what portion of the task subgraph is run in response to a particular command, you can get a failure, or not.

**Comment by dwijnand** [comment]
Ugh. sbt should do better than this. I've filed this as https://github.com/sbt/sbt/issues/3018.

**Comment by xuwei-k** [comment]
https://github.com/rickynils/scalacheck/pull/326
