### ISSUE TITLE
Gen.pick randomness questioned

### ISSUE THREAD

**Issue by bugfoot** [rickynils/scalacheck#332]
According my observations detailed in [this StackOverflow post](http://stackoverflow.com/questions/43839988/is-scalachecks-gen-pick-really-random/43846693), `Gen.pick` is seemingly not randomly picking elements from a list as it claims to.
As explained by [this reply](http://stackoverflow.com/a/43846693/4169924) by [ashawley](http://stackoverflow.com/users/73449/ashawley):

> It has everything to do with Scalacheck's heurisitic.
> There may be a bug, but consider what it's doing. It is randomly choosing to include or not include values at the beginning, but if not enough are chosen by the end, than Scalacheck forces to pick at the end.

(see code sample and more explanation in the [reply](http://stackoverflow.com/a/43846693/4169924))
I can't consider this behaviour random, hence I raised this question as an issue here.

**Comment by ashawley** [comment]
Well, `pick` is randomly selecting values from a set. However, it has sacrificed picking equally among the values and favors the end of the list because the code is trying to do iterate through the list lazily.

In your example, yhe odds of picking the first item is 1 in 50 or 2%.  Therefore, the odds of picking the first 3 items is  `1 / 50 * 1 / 49 * 1 /48` or about 1 in 10,000.

Maybe if you ran `reverse` on your list, or `shuffle`, you'd get a better distribution of picks with `pick`.

Because Scalacheck is a generic property testing library, I predict it can't do either of these things without sacrificing performance for arbitrary-sized collections.

I'm responsible for bringing up the b-word at Stack Overflow. :-)  This is a good issue to raise here, IMO.  Will probably garner a better explanation.

**Comment by bugfoot** [comment]
You are right @ashawley that I could compensate for `Gen.pick`'s skewed results by shuffling, but the underlying bug should be corrected in `pick`'s source code as [SergGr](http://stackoverflow.com/users/182660/serggr) pointed out in [this StackOverflow reply](http://stackoverflow.com/a/43857884/4169924), with solution also proposed.

**Comment by ashawley** [comment]
I actually was confused about the statistics and made some incorrect statements.

I don't see what's pointed out at SergGr's post.

To be honest, I should probably actually run your code and someone should write an actual test to verify it is an issue.  Your code and the way it's bootstrapped is a little unorthodox, so that needs to be sorted out, IMO.

**Comment by ashawley** [comment]
This can be closed since #333 was merged
