### ISSUE TITLE
Shrinking two generators sometimes presents strange ORIGINAL values.

### ISSUE THREAD

**Issue by rickynils** [rickynils/scalacheck#55]
```
scala> val p = forAll(choose(1000,2000), choose(1,2000))(_ > _)
p: org.scalacheck.Prop = Prop

scala> p.check
! Falsified after 0 passed tests.
> ARG_0: 0
> ARG_0_ORIGINAL: 1082
> ARG_1: 0
> ARG_1_ORIGINAL: 832
```

**Comment by joshcough** [comment]
I'm seeing similar strange behavior to this in 1.12.2. I sincerely hope this isn't me doing something wrong. If so, I apologize in advance, and if you could help me understand it, I'd really appreciate it.

The strange behavior happens in my [Engines](https://github.com/joshcough/Engines/) project (which is very small and easily cloneable), and is hopefully easily reproducible. Also, it might be worth mentioning that I've explicitly set parallelExecution := false in my build.sbt.

Onto the strange behavior. I print out the input given to each test. I regularly get many passing tests, and then a sudden (relatively) unexpected failure. When a test fails, one of two weird things happen: 

 * The ARG_0 printed by scalacheck not the same as what I print out. For example:

ORDERS:
	Order(86,c,Bid,TEST,74,254.43873234320026)
	Order(88,c,Bid,TEST,62,393.91951898451197)

[info] ! StockTests.piles of orders: Falsified after 0 passed tests.
[info] > Labels of failing property: 
[info] more bids than asks
[info] > ARG_0: List("Order(86,c,Bid,TEST,74,254.43873234320026)", "Order(87,c,Ask,TEST,105,244.58452200355075)", "Order(88,c,Bid,TEST,62,393.91951898451197)")

Notice that ARG_0 has 3 elements, but my test (which prints them immediately) only seems to get two. 

 * Or something even stranger happens, which seems to be what you are describing in this bug. I get some number of orders, ARG_0 has more orders than that, and ARG_0_ORIGINAL has even more orders!

ORDERS:
	Order(131,c,Bid,TEST,149,631.4725771598463)
	Order(133,c,Bid,TEST,62,944.4183612314257)

[info] ! StockTests.piles of orders: Falsified after 0 passed tests.
[info] > Labels of failing property: 
[info] more bids than asks
[info] > ARG_0: List("Order(131,c,Bid,TEST,149,631.4725771598463)", "Order(132,c,Ask,TEST,209,629.8105309112339)", "Order(133,c,Bid,TEST,62,944.4183612314257)")
[info] > ARG_0_ORIGINAL: List("Order(130,c,Bid,TEST,37,654.0004456068554)", "Order(131,c,Bid,TEST,149,631.4725771598463)", "Order(132,c,Ask,TEST,209,629.8105309112339)", "Order(133,c,Bid,TEST,62,944.4183612314257)", "Order(134,c,Bid,TEST,234,875.9020201131154)", "Order(135,c,Ask,TEST,237,661.8659108046078)")

And strangest yet, the test is checking stock.bids.nonEmpty. I print it out immediately before this check and see "nonEmpty: true", and yet the test still fails. That one I can only assume is a bug in Scalacheck. 

Please let me know if there is anything I can do to help you track this down and/or understand it. And once again, I sincerely hope it's not a simple bug in my code or something I'm overlooking. But I did spend several hours trying to understand it before deciding to send this in.

**Comment by joshcough** [comment]
Sorry, I should have added that the test code that fails is here: https://github.com/joshcough/Engines/blob/master/src/test/scala/com/joshcough/engines/exchange/ExchangeProperties.scala.

I will try to produce a smaller, more self contained version, but cannot do that immediately.

**Comment by joshcough** [comment]
Hello, s11001001 has explained to me the behavior here: 

"<orig> try try try <last failure> <success, discarded> and ARG_0 = last failure"

So, what I see printed is a legit passing case, and ARG_0 is the one prior to that, and it failed. I'm sorry that I didn't know about that.

**Comment by joshcough** [comment]
Just wanted to leave one more comment here. Feel free to ignore this, since I should have know and/or read the documentation. But given that I didn't know that the shrinking was happening automatically, it seems like some confusing things could potentially be improved with only minor changes.

ARG_0 and ARG_0_ORIGINAL get printed, but not the argument for the test that actually passed (if it was printed, I didn't see it anywhere). Maybe printing out something that explicitly states that shrinking is happening, and/or changing the names to ARG_0_OF_SMALLEST_FAILURE, ARG_O_ORIGINAL_FAILURE, and maybe printing out ARG_0_OF_PASSING_TEST, or some other similar strategy.

Additionally, I unfortunately spent a good deal of time examining the print outs from the last test, thinking that that was the one that failed. Once again, my fault, I should have known. But I think printing the arguments out like I mentioned above would have also made it clear that the print text that I was looking at was for the one that passed. 

I hope you find this productive.
